import { Piece } from './types';

export const INITIAL_PIECES: Piece[] = [
  { type: 'chariot', color: 'red', position: [0, 0] },
  { type: 'horse', color: 'red', position: [1, 0] },
  { type: 'elephant', color: 'red', position: [2, 0] },
  { type: 'advisor', color: 'red', position: [3, 0] },
  { type: 'general', color: 'red', position: [4, 0] },
  { type: 'advisor', color: 'red', position: [5, 0] },
  { type: 'elephant', color: 'red', position: [6, 0] },
  { type: 'horse', color: 'red', position: [7, 0] },
  { type: 'chariot', color: 'red', position: [8, 0] },
  { type: 'cannon', color: 'red', position: [1, 2] },
  { type: 'cannon', color: 'red', position: [7, 2] },
  { type: 'soldier', color: 'red', position: [0, 3] },
  { type: 'soldier', color: 'red', position: [2, 3] },
  { type: 'soldier', color: 'red', position: [4, 3] },
  { type: 'soldier', color: 'red', position: [6, 3] },
  { type: 'soldier', color: 'red', position: [8, 3] },

  { type: 'chariot', color: 'black', position: [0, 9] },
  { type: 'horse', color: 'black', position: [1, 9] },
  { type: 'elephant', color: 'black', position: [2, 9] },
  { type: 'advisor', color: 'black', position: [3, 9] },
  { type: 'general', color: 'black', position: [4, 9] },
  { type: 'advisor', color: 'black', position: [5, 9] },
  { type: 'elephant', color: 'black', position: [6, 9] },
  { type: 'horse', color: 'black', position: [7, 9] },
  { type: 'chariot', color: 'black', position: [8, 9] },
  { type: 'cannon', color: 'black', position: [1, 7] },
  { type: 'cannon', color: 'black', position: [7, 7] },
  { type: 'soldier', color: 'black', position: [0, 6] },
  { type: 'soldier', color: 'black', position: [2, 6] },
  { type: 'soldier', color: 'black', position: [4, 6] },
  { type: 'soldier', color: 'black', position: [6, 6] },
  { type: 'soldier', color: 'black', position: [8, 6] },
];
